Implemented code to test cassljs run command on Firefox and Chrome
omzn/casljs pull request #12
Opened 2022-07-18 04:24 UTC by mass-0910

# 変更点
- ページのテストを実装しました。
- テスト実装に伴い、.gitignoreも変更しました。
- workflowsも記述したため、push毎にActionsにてテストが走ります。
- ローカルでテストを実行する方法はtest/README.mdに書いてあります。

# Github Actionsでのテスト
- 1回のテストにはだいたい10分くらいかかります。
- OSはwindows、Linux、MacOSを使用し、ブラウザはFirefox、Chromeを使ってテストします。
- 現在Actionsにてテストが走るトリガ条件には、リポジトリへのpushを指定しておりますが、もっとよさそうな実行タイミングがあれば教えてください。(Github Actionsをよく知らなくて適切なトリガがわからない:sweat:)

2022-07-18 16:09 UTC, Hiroya-W requested changes
PRありがとうございます！
CIでのテストは必要だと思っていたのですが、なかなか重たそうなタスクだったので手が付けられませんでした...。これがあると、間違いなく快適になります！！！！！ありがとうございます！

今後、メンテナンスしていくことなど考えて、気になるところ、コメント書きました。修正に関しては、また良ければ、お話させていただきたいです :bow: よろしくお願いします。

2022-07-18 16:09 UTC, Hiroya-W commented on .github/workflows/test.yml
> +on: [push]
CIのトリガーには、push、pull_requestをつけることをよくします。
一見、2重に走っているように思いますが、今回のPRのようなfork先からのPRでも、本家リポジトリ上でCIが実行されるようになるはずです。
そうすれば、このPR上でテストをすべてpassしていることが確認出来るようになって嬉しいです！
```suggestion
on:
  push:
  pull_request:
```

2022-07-18 16:09 UTC, Hiroya-W commented on .github/workflows/test.yml
> +          firefox-version: "84.0"
Windowsの場合は、Ubuntu、macOSのように `latest` ではなく、`84.0`でなければならない理由にはどのようなものがあるのでしょうか？教えていただければ嬉しいです :bowing_man:

2022-07-18 16:09 UTC, Hiroya-W commented on .github/workflows/test.yml
> +      # テストの依存モジュールをインストールする
webdriverのインストール部分ですが、webdriver_managerを使えば、管理がしやすくなりそうでしょうか？webdriver_managerはseleniumのドキュメントにあるPythonのサンプルコードでも利用されているようです。
https://github.com/SergeyPirogov/webdriver_manager
https://www.selenium.dev/ja/documentation/webdriver/getting_started/install_drivers/

2022-07-18 16:09 UTC, Hiroya-W commented on test/requirements.txt
> +pytest
本質ではないですが、Pythonは勝手に壊れることがあるので、pipenvもしくはpeotryを利用して、ライブラリのバージョンを固定出来るならしておきたいです。
使い方が分からない場合は、一旦このまま、バージョンの指定だけしておくことにして、マージできた後に、別PRで対応しようかなと思っています！
```suggestion
selenium == 4.3.*
pytest == 7.1.*
```

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    if os.name == "nt" and os.path.exists("geckodriver.exe"):
ここも、webdriver_managerで環境の差異を吸収できそうな気がします

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +]
これだと管理が厳しそうなので、こんな感じに変えてみるのはどうでしょうか

```suggestion
import glob
import itertools
browsers = ["Firefox", "Chrome"]
sample_files = sorted(glob.glob("samples/**/*.cas", recursive=True))
test_data = list(itertools.product(browsers, sample_files))
```

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    if os.name == "nt" and os.path.exists("geckodriver.exe"):
あぁ、GitHub APIを利用するので、Tokenを要求するようになっているんですね...。
GitHub Actionsでは設定しなくとも、 `secrets.GITHUB_TOKEN` で取得出来るようになっているので、それを環境変数にセットするようにするのがいいかもしれないです。

2022-07-18 16:09 UTC, Hiroya-W commented on .github/workflows/test.yml
> +      # テストの依存モジュールをインストールする
GitHub APIを利用するので、Tokenを利用するんですね。それを避けるのに、自分でdriverを取得するようにしたのかな、というのを感じました

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    if os.name == "nt" and os.path.exists("geckodriver.exe"):
後、ChromeとFireFoxのdriverを作成するときに、各問題ごとにGitHub APIを利用してバージョンを確認してしまう、N+1があって、いくらRateLimitがあっても足りないので、そこの問題も対処しないといけないですね。
driverって使いまわしが出来ないんでしょうか...？

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    driver = init_firefox_driver()
webdriver_managerを使うと、(ブラウザ数xテストの数)回のGitHub APIアクセスが起きてしまうので、おそらくここをなんとかすればいいのかな、と思っています。
そもそも、何度もdriverを生成せずに、初期化したものを使いまわす、みたいなことは出来ないんでしょうか...？
グローバルに置くのが一番簡単ですが、これでもいけるのかな、というのを思っています

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    return driver
Firefoxや他ブラウザであっても、同じ処理になりそうですね。
optionのみ設定したdriverを返して、開くURLの指定を1箇所で出来そうならその方がいいかもしれません

2022-07-18 16:09 UTC, Hiroya-W commented on .github/workflows/test.yml
> +        run: python -m pytest --junit-xml result-${{ matrix.os }}.xml
pytestのparametrizeを使う場合は、テストケース名がいい感じにつくので、`-v`で表示してもいいかも、と思いました。最後にSummaryを表示していただいていますが、どのテストが落ちているのかは、この表示があると分かりやすいかもしれません。

```
# 例
terminal_casl2comet2_test.py::test_casl2comet2_run[Firefox-samples/program1/sample11.cas] PASSED   
```


```suggestion
        run: python -m pytest -v --junit-xml result-${{ matrix.os }}.xml
```

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    if not os.path.exists("test_result"):
`test_result` は複数ヶ所で利用しているので、変数として定義して利用するようにしてもいいと思います。
パスの結合時、`os.path.join`では`/`があるかどうかを意識しないといけないなど少し戸惑うことがありますが、標準パッケージの `pathlib` を使うとやりやすくなるかもしれません。今回は特に複雑なことはしないので、別にどちらでも大丈夫です！

```py
TEST_RESULT_DIR = "test_result"
```

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    if not os.path.exists("test_result"):
細かいですが、`test_results`の方が適切かもですね

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    expect_file = os.path.join("test_expect", os.path.basename(casl2_file) + ".out")
`test_results`で書いてしまったので、`test_expect`も同様にすると良いと思います。

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +        if src:
コメントアウトの戻し忘れかな
```suggestion
        for src in sample_files:
```

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    expect_file = os.path.join("test_expect", os.path.basename(casl2_file) + ".out")
これも`test_expects`かな、細かい...。

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +if __name__ == "__main__":
これって、pytestの実行とほぼ内容は同じでしょうか？
指定したブラウザで、指定したテストだけ実行したいという要求があるのは分かるのですが、それはpytestだと`-k`オプションが利用できます。`-k`オプションは、簡単に説明すると、指定したキーワードを含むテストだけを実行出来るものです。
テスト名を表示するために、`-v`オプションをつけて実行するコマンド例はこんな感じです。この場合は、Chromeでsample11.casのみテストを実行出来ると思います。

```
pytest -v -k "Chrome and sample11.cas"
```

2022-07-18 16:09 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +if __name__ == "__main__":
コードもpytestが利用しているところと共通化出来るのでこの方が嬉しいかな、と思います！

2022-07-18 16:40 UTC, mass-0910 commented on .github/workflows/test.yml
> +          firefox-version: "84.0"
すみません、ただ単にbrowser-actions/setup-firefoxアクションがwindowsで動作する際にfirefox-version: latestをサポートしてなかったためです...
windowsでbrowser-actions/setup-firefoxを使用しているワークフローをwebで見つけ、そこで使用されているバージョンが`84.0`でしたので、私もそのバージョンを使用しました。

以下が「windowsで動作する際にfirefox-version: latestをサポートしてない」問題に該当するissueです。
https://github.com/browser-actions/setup-firefox/issues/252

2022-07-18 16:43 UTC, mass-0910 commented on .github/workflows/test.yml
> +      # テストの依存モジュールをインストールする
ただ単に「テストのセットアップスクリプト(`setup_test.sh`または`setup_test.ps1`)も使えるかも一緒に試したろ」という気持ちです

2022-07-18 16:47 UTC, mass-0910 commented on test/requirements.txt
> +pytest
これは確かにそうでして、Pythonが勝手に壊れることは今回は特に考えていませんでした。(私も昔勝手に壊れました)
モジュールのインストールにpoetryを使用している例をよく見るので、もしよろしければ使用するコードを書いていただけましたら幸いです。
今回はバージョン指定にとどめておきます。

2022-07-18 16:53 UTC, mass-0910 commented on .github/workflows/test.yml
> +      # テストの依存モジュールをインストールする
ごめんなさい、webdriver_managerというPythonモジュールがあるんですね,,,（actionかと思った）
確かにwebdriver_managerを使用したほうがよさそうですね
使うように変更してみます。

2022-07-18 16:56 UTC, mass-0910 commented on .github/workflows/test.yml
> +      # テストの依存モジュールをインストールする
いや、確かにテスト毎にGtihub Tokenを使用するのは流石に避けたほうがいいかな...？

2022-07-18 16:59 UTC, mass-0910 commented on test/terminal_casl2comet2_test.py
> +    driver = init_firefox_driver()
おそらくできます。
書き直してみます。

2022-07-18 17:06 UTC, mass-0910 commented on test/terminal_casl2comet2_test.py
> +        if src:
```suggestion
        for src in sample_files:
        # src = "samples/program1/sample16.cas"
        # if src:
```
すみません、これ上記が正しいです...
sample16.casのタイムアウトを何度も確かめてたときの名残です...
コメントアウト部は消しても構いません

2022-07-18 17:09 UTC, mass-0910 commented on test/terminal_casl2comet2_test.py
> +if __name__ == "__main__":
テスト中にstdoutを使用したデバッグを行う際によく使用していました。
おそらくもう必要ないので、pytest部と共通にしてもいいかもしれません。
(実は最初はpytestで実行することを考えておらず、その時の名残で__main__部を残してましたすみません...)

2022-07-18 18:33 UTC, mass-0910 commented
現時点でご指摘にあったwebdriver_manager関連**以外**の全ての変更を行いました。
その他にも、タイムアウト値を3秒から5秒に変更しました。(たまにタイムアウトするため)

webdriver_managerは今後テストするブラウザが増えることも踏まえ、積極的に導入するべきかと思いますが、なにぶん私がGithub APIに疎いため導入できるかどうかがわかりません。
一度導入を試みてみますが、もしできなければすみません:bow:

2022-07-18 19:27 UTC, mass-0910 commented
只今、webdriver_managerの導入が完了しました。
各テスト毎にドライバの初期化を行わないように変更しましたので、おそらく上限までTokenを使用するなんてことはないかと思われます（？）

2022-07-18 19:28 UTC, mass-0910 commented
Actionsの実行時間も5分くらいまで縮まっていい感じ

2022-07-19 00:50 UTC, Hiroya-W commented on .github/workflows/test.yml
> +          firefox-version: "84.0"
Issue、確認しました。確かにサポートしていないようですね...。調査ありがとうございます。
現状では、`84.0`を指定するのが良さそうです。latestをサポートしていない件とIssueへのリンクを `test.yml` 内にも記載しておいていただけますか？

2022-07-19 02:39 UTC, Hiroya-W reviewed
修正ありがとうございます！すごく良くなったと思います！！！
残り、CIへのコメントの追記だけお願いします :pray:

2022-07-19 02:39 UTC, Hiroya-W commented on test/terminal_casl2comet2_test.py
> +    driver = init_firefox_driver()
fixtureのscopeで実現出来るんですね！
これあまり使ったことがなくて、勉強になりました！

2022-07-19 02:39 UTC, Hiroya-W commented on .github/workflows/test.yml
> +      # windowsのときはFirefoxの84.0をインストールする
コメントに latest が対応していないことを追記しておいて、latestへの対応があれば統合出来るように残しておくと良さそうです

```suggestion
      # windowsのときはFirefoxの84.0をインストールする
      # windowsではfirefox-version: "latest"をサポートしていないことが報告されています
      # https://github.com/browser-actions/setup-firefox/issues/252
```

2022-07-19 03:59 UTC, mass-0910 commented
ymlにコメントを追加しました。

2022-07-19 04:01 UTC, Hiroya-W approved these changes
ありがとうございます！
LGTMです！

2022-07-19 04:05 UTC, mass-0910 commented
ちょっとテストコードにミスがあったので新しいコミットを行います。

2022-07-19 04:11 UTC, mass-0910 commented
ドライバのインストール先フォルダ名を間違えていたので修正しました。
これで.gitignoreによってドライバがバージョン管理から無視されるはずです。

2022-07-19 04:46 UTC, Hiroya-W approved these changes

2022-07-29 14:10 UTC, merged